spring.application.name=Literalura
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=Alondra.

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.format-sql=true
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql=off
logging.level.org.springframework=off
logging.level.com.zaxxer.hikari=off